### ISSUE TITLE
80x prescription

### ISSUE THREAD

**Issue by chrisneu** [hsatoshi/ttH-LeptonPlusJets#8]
Hi Satoshi,

I ran your prescription 
https://github.com/hsatoshi/ttH-LeptonPlusJets/blob/satoshi_cleanup_80x/README.txt
today and it works well. A couple things I would add for ultra-beginners:

When running on lxplus, one should run these codes in advance of anything:

 source /cvmfs/cms.cern.ch/cmsset_default.csh
 setenv SCRAM_ARCH slc6_amd64_gcc530

Also, it should be noted that the first 2 times one tries to compile, errors are encountered from the following files:
  MiniAODBoostedObjects_xr.cc
  ttH-LeptonPlusJetsAnalysisCode_xr.cc

One should re-compile after each failure; on the third try the compilation succeeds.

Can you add these details to the recipe? 

Thanks,

C

**Comment by hsatoshi** [comment]
Thank you for your feedback.
I added these two points to the recipe : 1e924d5a9c33dcc98fc27c05ba910a19c3a79ee5

Especially, the compile error at the first time needs to be understood (and I try).
I keep this issue open.
